CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  email TEXT,
  display_name TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS privacy_settings (
  user_id TEXT PRIMARY KEY REFERENCES users(id),
  screenshot_policy TEXT NOT NULL DEFAULT 'manual',
  local_only_mode BOOLEAN NOT NULL DEFAULT TRUE,
  sync_consent TEXT NOT NULL DEFAULT 'unknown',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS retention_jobs (
  id BIGSERIAL PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  job_type TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  run_after TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  payload JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE classes ADD COLUMN IF NOT EXISTS owner_user_id TEXT;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS owner_user_id TEXT;
ALTER TABLE interactions ADD COLUMN IF NOT EXISTS owner_user_id TEXT;
ALTER TABLE gaps ADD COLUMN IF NOT EXISTS owner_user_id TEXT;
